# Generated by Django 5.2.7 on 2025-10-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='practice_time',
            field=models.DurationField(default='00:00:00'),
        ),
    ]
