# Generated by Django 5.2.7 on 2025-11-18 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_log_practice_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='instrument',
            field=models.CharField(help_text='Name of instrument practiced.'),
        ),
        migrations.AlterField(
            model_name='log',
            name='practice_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date practiced.'),
        ),
        migrations.AlterField(
            model_name='log',
            name='practice_time',
            field=models.DurationField(default='00:00:00', help_text='Time practiced, in hours-minutes-seconds.'),
        ),
        migrations.AlterField(
            model_name='log',
            name='song',
            field=models.CharField(default='No song', help_text='Name of song practiced.'),
        ),
    ]
