# Generated by Django 5.2.7 on 2025-11-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_log_instrument_alter_log_practice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='song',
            field=models.CharField(default='General practice', help_text='Name of song practiced.'),
        ),
    ]
