# Generated by Django 5.2.7 on 2025-12-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_log_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='practice_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='practice_time',
            new_name='duration',
        ),
    ]
